### ISSUE TITLE
Line breaks not rendered properly in post text

### ISSUE THREAD

**Issue by ryanbooker** [VernissageApp/Home#10]
Steps:
1. Type text with line breaks or paste text with line breaks from an alternate source
2. Save post
3. Note that the line breaks aren't rendered in the post view

The same text _does_ render properly on Pixelfed and in the Pixelfed app.

e.g. https://pixelfed.social/p/ryanbooker/540050693552813867

**Comment by mczachurski** [comment]
Fixed in 1.0 (build 73).
