### ISSUE TITLE
Extra spaces rendered in post text

### ISSUE THREAD

**Issue by ryanbooker** [VernissageApp/Home#11]
I'm not sure how to reproduce this issue, however it is apparent on the following post:

e.g. https://pixelfed.social/p/ryanbooker/539324982674354129

This time the line breaks are rendered, but there is also a an extra space at the start of each "paragraph". This extra space is not shown on Pixelfed or the Pixelfed app.

**Comment by mczachurski** [comment]
Fixed in 1.0 (build 73).
